version: "3"
services:
  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - myredis
    env_file:
      - myapp-variables.env
  myredis:
    image: redis
    container_name: myredis
    restart: always
    ports:
      - "6379:6379"